[
    {'activeScore': -1, 
     'activityCalories': 0, 
     'caloriesBMR': 890, 
     'caloriesOut': 890, 
     'distances': 
        [
            {'activity': 'total', 'distance': 0}, 
            {'activity': 'tracker', 'distance': 0}, 
            {'activity': 'loggedActivities', 'distance': 0}, 
            {'activity': 'veryActive', 'distance': 0}, 
            {'activity': 'moderatelyActive', 'distance': 0}, 
            {'activity': 'lightlyActive', 'distance': 0},
            {'activity': 'sedentaryActive', 'distance': 0}], 
    'fairlyActiveMinutes': 0, 
    'lightlyActiveMinutes': 0, 
    'marginalCalories': 0, 
    'sedentaryMinutes': 1440, 
    'steps': 0, 
    'veryActiveMinutes': 0}, 
    
    {'activeScore': -1, 
     'activityCalories': 0, 
     'caloriesBMR': 890, 
     'caloriesOut': 890, 
     'distances': [{'activity': 'total', 'distance': 0}, 
                   {'activity': 'tracker', 'distance': 0}, 
                   {'activity': 'loggedActivities', 'distance': 0}, 
                   {'activity': 'veryActive', 'distance': 0}, 
                   {'activity': 'moderatelyActive', 'distance': 0}, 
                   {'activity': 'lightlyActive', 'distance': 0}, 
                   {'activity': 'sedentaryActive', 'distance': 0}], 
    'fairlyActiveMinutes': 0, 
    'lightlyActiveMinutes': 0, 
    'marginalCalories': 0, 
    'sedentaryMinutes': 1440, 
    'steps': 0, 
    'veryActiveMinutes': 0}, 
    
    {'activeScore': -1, 
     'activityCalories': 0, 
     'caloriesBMR': 890, 
     'caloriesOut': 890, 
     'distances': [{'activity': 'total', 'distance': 0}, 
                   {'activity': 'tracker', 'distance': 0}, 
                   {'activity': 'loggedActivities', 'distance': 0}, 
                   {'activity': 'veryActive', 'distance': 0}, 
                   {'activity': 'moderatelyActive', 'distance': 0}, 
                   {'activity': 'lightlyActive', 'distance': 0}, 
                   {'activity': 'sedentaryActive', 'distance': 0}],
    'fairlyActiveMinutes': 0, 
    'lightlyActiveMinutes': 0, 
    'marginalCalories': 0, 
    'sedentaryMinutes': 1440, 
    'steps': 0, 
    'veryActiveMinutes': 0}, 
    
    {'activeScore': -1, 
     'activityCalories': 0, 
     'caloriesBMR': 890, 
     'caloriesOut': 890, 
     'distances': [{'activity': 'total', 'distance': 0}, 
                   {'activity': 'tracker', 'distance': 0}, 
                   {'activity': 'loggedActivities', 'distance': 0}, 
                   {'activity': 'veryActive', 'distance': 0}, 
                   {'activity': 'moderatelyActive', 'distance': 0}, 
                   {'activity': 'lightlyActive', 'distance': 0}, 
                   {'activity': 'sedentaryActive', 'distance': 0}], 
    'fairlyActiveMinutes': 0, 
    'lightlyActiveMinutes': 0, 
    'marginalCalories': 0, 
    'sedentaryMinutes': 1440, 
    'steps': 0, 
    'veryActiveMinutes': 0}, 
    
    {'activeScore': -1, 
     'activityCalories': 0, 
     'caloriesBMR': 890, 
     'caloriesOut': 890, 
     'distances': [{'activity': 'total', 'distance': 0}, 
                   {'activity': 'tracker', 'distance': 0}, 
                   {'activity': 'loggedActivities', 'distance': 0}, 
                   {'activity': 'veryActive', 'distance': 0}, 
                   {'activity': 'moderatelyActive', 'distance': 0}, 
                   {'activity': 'lightlyActive', 'distance': 0}, 
                   {'activity': 'sedentaryActive', 'distance': 0}], 
    'fairlyActiveMinutes': 0, 
    'lightlyActiveMinutes': 0, 
    'marginalCalories': 0, 
    'sedentaryMinutes': 1440, 
    'steps': 0, 
    'veryActiveMinutes': 0}, 
    
    {'activeScore': -1, 
     'activityCalories': 0, 
     'caloriesBMR': 890, 
     'caloriesOut': 890, 
     'distances': [{'activity': 'total', 'distance': 0}, 
                   {'activity': 'tracker', 'distance': 0}, 
                   {'activity': 'loggedActivities', 'distance': 0}, 
                   {'activity': 'veryActive', 'distance': 0}, 
                   {'activity': 'moderatelyActive', 'distance': 0}, 
                   {'activity': 'lightlyActive', 'distance': 0}, 
                   {'activity': 'sedentaryActive', 'distance': 0}], 
    'fairlyActiveMinutes': 0, 
    'lightlyActiveMinutes': 0, 
    'marginalCalories': 0, 
    'sedentaryMinutes': 1440, 
    'steps': 0, 
    'veryActiveMinutes': 0}, 
    
    {'activeScore': -1, 
     'activityCalories': 0, 
     'caloriesBMR': 890, 
     'caloriesOut': 890, 
     'distances': [{'activity': 'total', 'distance': 0}, 
                   {'activity': 'tracker', 'distance': 0}, 
                   {'activity': 'loggedActivities', 'distance': 0}, 
                   {'activity': 'veryActive', 'distance': 0}, 
                   {'activity': 'moderatelyActive', 'distance': 0}, 
                   {'activity': 'lightlyActive', 'distance': 0}, 
                   {'activity': 'sedentaryActive', 'distance': 0}], 
    'fairlyActiveMinutes': 0, 
    'lightlyActiveMinutes': 0, 
    'marginalCalories': 0, 
    'sedentaryMinutes': 1440, 
    'steps': 0, 
    'veryActiveMinutes': 0}]